### ISSUE TITLE
If this could provide the line number that would be much better

### ISSUE THREAD

**Issue by aurexav** [pascalkuthe/imara-diff#8]

**Comment by pascalkuthe** [comment]
Please provide more detailed description of what kind of API you are looking for. The current API can absolutly provide line numbers and is used to that effect in helix and gitoxide. 

in general opening an issue without providing a description is basically never useful so please provide more details in the future if interacting with opensource projects

**Comment by AurevoirXavier** [comment]
> Please provide more detailed description of what kind of API you are looking for. The current API can absolutly provide line numbers and is used to that effect in helix and gitoxide.
> 
> in general opening an issue without providing a description is basically never useful so please provide more details in the future if interacting with opensource projects

For example, check this GitHub diff https://github.com/pascalkuthe/imara-diff/pull/6/files.

Hope that we can have these nifty numbers.

<img width="145" alt="image" src="https://github.com/pascalkuthe/imara-diff/assets/16152305/b61602e6-7f32-4e93-bf58-d1c3af5be40f">

**Comment by pascalkuthe** [comment]
you can totally compute those numbers with the current API but this is a low-level crate, not an application so you need to specify  *what API* you are looking for
